-- ---------------------------------------------------------------------------
-- One-off setup. Run as SYSADMIN/SECURITYADMIN, not by the pipeline.
--
-- Two warehouses on purpose: loading is tiny and bursty, transformation is
-- bigger and batched. Sharing one warehouse means dbt's size is also paid on
-- every small COPY. See docs/cost_model.md.
-- ---------------------------------------------------------------------------

CREATE WAREHOUSE IF NOT EXISTS WH_INGEST_XS
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60          -- seconds; loads are short, idle time is pure cost
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'PUT/COPY/MERGE for the weather batch pipeline';

CREATE WAREHOUSE IF NOT EXISTS WH_TRANSFORM_S
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  STATEMENT_TIMEOUT_IN_SECONDS = 1800   -- a dbt model running >30 min is a bug
  COMMENT = 'dbt runs';

CREATE DATABASE IF NOT EXISTS WEATHER;

CREATE SCHEMA IF NOT EXISTS WEATHER.RAW        COMMENT = 'Landed as-is, contract enforced, never edited by hand';
CREATE SCHEMA IF NOT EXISTS WEATHER.STAGING    COMMENT = 'dbt staging models';
CREATE SCHEMA IF NOT EXISTS WEATHER.MARTS      COMMENT = 'dbt marts, consumed by BI';
CREATE SCHEMA IF NOT EXISTS WEATHER.OPS        COMMENT = 'Load audit + quarantine';

CREATE ROLE IF NOT EXISTS LOADER;
CREATE ROLE IF NOT EXISTS TRANSFORMER;
CREATE ROLE IF NOT EXISTS ANALYST;

GRANT USAGE ON WAREHOUSE WH_INGEST_XS TO ROLE LOADER;
GRANT USAGE ON WAREHOUSE WH_TRANSFORM_S TO ROLE TRANSFORMER;
GRANT USAGE ON WAREHOUSE WH_TRANSFORM_S TO ROLE ANALYST;

GRANT USAGE ON DATABASE WEATHER TO ROLE LOADER;
GRANT USAGE ON DATABASE WEATHER TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE WEATHER TO ROLE ANALYST;

GRANT ALL ON SCHEMA WEATHER.RAW TO ROLE LOADER;
GRANT ALL ON SCHEMA WEATHER.OPS TO ROLE LOADER;
GRANT USAGE ON SCHEMA WEATHER.RAW TO ROLE TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA WEATHER.RAW TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA WEATHER.RAW TO ROLE TRANSFORMER;
GRANT ALL ON SCHEMA WEATHER.STAGING TO ROLE TRANSFORMER;
GRANT ALL ON SCHEMA WEATHER.MARTS TO ROLE TRANSFORMER;

GRANT USAGE ON SCHEMA WEATHER.MARTS TO ROLE ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA WEATHER.MARTS TO ROLE ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA WEATHER.MARTS TO ROLE ANALYST;
